version: '1.0'
stages:
  - prepare
  - test
  - 'integration test'
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'Himanshurock/Spring-Data-MongoDB-Example'
    revision: master
    git: github
  run_unit_tests:
    title: Compile/Unit test
    stage: test
    image: 'maven:3.5.2-jdk-8-alpine'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository test 
  run_integration_tests:
    title: Integration test
    stage: 'integration test'
    image: maven:3.5.2-jdk-8-alpine
    commands:
     - env
     - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository integration-test
    environment:
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.host=mongo
    services:
      composition:
        mongo:
          image: mongo:latest
          ports:
            - 27017
